# Generated by Django 3.1.5 on 2021-02-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerHistory',
            new_name='OrderHistory',
        ),
    ]
