# Generated by Django 3.1.5 on 2021-02-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0004_auto_20210217_0853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Bike_id',
            new_name='Bike',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Customer_id',
            new_name='Customer',
        ),
    ]
