# Generated by Django 3.1.5 on 2021-02-17 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0005_auto_20210217_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Bike',
            new_name='Bike_id',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Customer',
            new_name='Customer_id',
        ),
    ]
