# Generated by Django 3.1.5 on 2021-02-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0006_auto_20210217_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike_status',
            old_name='Bike_id',
            new_name='Bike',
        ),
        migrations.RenameField(
            model_name='customerinfo',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='customerlocation',
            old_name='Customer_id',
            new_name='Customer',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Bike_id',
            new_name='Bike',
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='Customer_id',
            new_name='Customer',
        ),
    ]
