# Generated by Django 3.1.5 on 2021-02-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0008_auto_20210217_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='Customer_age',
            field=models.IntegerField(max_length=100),
        ),
    ]
