# Generated by Django 3.1.5 on 2021-02-18 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0009_auto_20210218_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercomplaints',
            name='Complaint_id',
        ),
    ]
