# Generated by Django 3.1.5 on 2021-02-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0010_remove_customercomplaints_complaint_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaints',
            name='Complaint_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
