# Generated by Django 3.1.5 on 2021-02-18 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0011_customercomplaints_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercomplaints',
            name='Complaint_Resolution',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customercomplaints',
            name='Complaint_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='End_location_latitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='End_location_longitude',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='End_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='Ride_Bill',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
