# Generated by Django 3.1.5 on 2021-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0012_auto_20210218_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='End_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='repair_bikes',
            name='Operator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BikeApp.operator_info'),
        ),
    ]
