# Generated by Django 3.1.5 on 2021-02-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeApp', '0013_auto_20210218_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='Customer_cardNumber',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customerinfo',
            name='Customer_age',
            field=models.IntegerField(),
        ),
    ]
